# This is just an example! Please see available options to customize Navidrome for your needs at
# https://www.navidrome.org/docs/usage/configuration-options/#available-options

MusicFolder = '/opt/music'
DataFolder = '/opt/navidrome'
CacheFolder = '/opt/navidrome/cache'
ScanSchedule = '@every 24h'
ImageCacheSize = '100MB'
TranscodingCacheSize = '100MB'
Address = '0.0.0.0'
Port = '4533'
LogLevel = 'warn'
